### ISSUE TITLE
How do we go about editing the margins?

### ISSUE THREAD

**Issue by tarunsrivastava145** [mcmanigle/OxThesis#6]

**Comment by mcmanigle** [comment]
Look at lines 82 - 86 of ociamthesis.cls.  The options on line 83 are for "no binding" (e.g. those intended for electronic submission) and the options on line 85 are for "binding" (e.g. printed and bound copies).  For full options, see http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/geometry/geometry.pdf
