### ISSUE TITLE
`\savequote` redefinition errors when running with `XeLaTeX`

### ISSUE THREAD

**Issue by shirdekel** [mcmanigle/OxThesis#8]
Running a document that uses `\savequote` with `ociamthesis.cls` using `XeLaTeX` leads to this error:

```
! Illegal unit of measure (pt inserted).
<to be read again> 
                   p
```

Running it using `pdflatex` works fine.

It seems that the problem is in the redefinition of `\savequote` here: https://github.com/mcmanigle/OxThesis/blob/973b346a19527f481fc2cbf203eb9a5af78c02a8/ociamthesis.cls#L388 

`px` can't be used in `xelatex`, so changing it to `pt` fixes the problem for me.

**Comment by mcmanigle** [comment]
Fixed; thank you! (Merge #e967f39)
